### ISSUE TITLE
May/June 2014 travels

### ISSUE THREAD

**Issue by kylef** [kylef/life#1]
### Tasks:
- [x] Flights (LDN > SF, SF > NY, NY > LDN)
- [x] WWDC Tickets
- [x] #inspect ticket
- [x] Accommodation (SF) - May 24th - June 8th
- [x] Accommodation (NY) - June 9th - June 15th
